version: '3.9'

services:
  worker:
    build: worker
    restart: always
    volumes:
      - ./worker:/usr/src/app
      - ./files-cloud:/files-cloud
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 550M
